# Generated by Django 5.0.2 on 2024-03-01 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disclaimer_api", "0001_initial"),
        ("user_api", "0002_alter_carryuser_date_disclaimer_signed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carryuser",
            name="disclaimer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="disclaimer_api.disclamer",
            ),
        ),
    ]
